### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by LuisOlivaresJ** [jfcabana/omg_dosimetry#2]
**Describe the bug**
ERROR: Cannot install omg-dosimetry==1.4.1 because this package versions have conflicting dependencies.

**To Reproduce**
1. Create a new conda environment ```conda create --name omg_d``` 
2. Install pip ```conda install pip```
3.  Install omg-dosimetry ```pip install omg-dosimetry```

**Screenshots**
![first desktop computer python 3__11_3](https://github.com/jfcabana/omg_dosimetry/assets/41806420/9256ac92-e4a2-4aad-a75d-9e8fded98914)

**Additional information**
I am using 
* conda 22.11.0 
* pip 23.1.2
* python 3.11.3

**Comment by LuisOlivaresJ** [comment]
I think the problem is the python version I am using (3.11.3). The package pymedphys 0.39 [requires python <3.11](https://github.com/pymedphys/pymedphys/blob/0.39.x/pyproject.toml#LL34C23-L34C23)

Creating an evironment with python 3.10 solves the issue ```conda create --name omg_d python=3.10```

**Comment by LuisOlivaresJ** [comment]
One question, 

When or where do you use ``omg_dosimetry/requirements.txt``? Is it needed for packaging?

I'm not sure but the content looks too long.  For example I don't have that file on [my proyect](https://github.com/LuisOlivaresJ/Dosepy) and the requirements.txt file from [pylinac](https://github.com/jrkerns/pylinac/blob/master/requirements.txt) looks pretty eassy.

Please let me know if I am missing something.

**Comment by jfcabana** [comment]
I don't believe `omg_dosimetry/requirements.txt` is used at all. I think we could delete this file.

**Comment by LuisOlivaresJ** [comment]
Fixed in #3
