### ISSUE TITLE
Python version <3.11 requirement

### ISSUE THREAD

**Issue by jfcabana** [jfcabana/omg_dosimetry#47]
Requirements indicates python <3.11, >=3.7. Latest Anaconda distribution base environnement version is 3.11. 

I can't recall why the <3.11 requirement was added. Does it still hold?

**Comment by LuisOlivaresJ** [comment]
Hi Jean,

I had not seen this issue until today. Sorry for the elapsed time.

Here is the answer #2. It is because a dependency conflict. pymedphys 0.39 [requires python <3.11](https://github.com/pymedphys/pymedphys/blob/0.39.x/pyproject.toml#LL34C23-L34C23)
