### ISSUE TITLE
Manual ROI selection for calibration.

### ISSUE THREAD

**Issue by LuisOlivaresJ** [jfcabana/omg_dosimetry#53]
Hello there,

In calibration module...

Once the image with the irradiated films is shown and I draw a manual ROI, a new one is created every time a click is released. That behaviour does no allow to change the RectangleSelector size, or move it to use the same RectangleSelector for another film. 

This is not an issue, so I labeled it as a possible enhancement. I think that it could be "user-friendly" to perform a ROI creation when a key is pressed instead when a click is released.

Let me know what do you think. I can work in that.
Cheers,

**Comment by jfcabana** [comment]
I know exactly what you mean, and it has always bothered me also :D I just never took the time to change it. If you are willing to work on it, please go ahead :)

**Comment by LuisOlivaresJ** [comment]
Working on it in branch `manual_roi_automatic`
